spring:
  application:
    name: EurekaClient

spring:
  profiles:
    active: "dev"

---

spring:
  profiles: dev

eureka:
  client:
    enabled: false

---

spring:
  profiles: local

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---

spring:
  profiles: cloud

security:
  basic:
    enabled: false